/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagementsystem;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ceyda
 */
public class MusteriEkle extends javax.swing.JFrame {

    /**
     * Creates new form MusteriEkle
     */
    Connection conn = null;
    PreparedStatement pst = null;
    Statement stmt = null;
    java.sql.ResultSet res = null;
    ResultSet rs = null;

    public MusteriEkle() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        conn = db.connect_db();
        odatipi();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_odano = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txt_giristarihi = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_telefonno = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_kaydet = new javax.swing.JButton();
        cb_odatipi = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_isim = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_soyisim = new javax.swing.JTextField();
        txt_dogumtarihi = new javax.swing.JFormattedTextField();
        txt_kimlikno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_adres = new javax.swing.JTextArea();
        txt_cikistarihi = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        txt_odano.setBackground(new java.awt.Color(255, 255, 255));
        txt_odano.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_odano.setForeground(new java.awt.Color(242, 190, 94));
        txt_odano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_odanoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_odano);
        txt_odano.setBounds(290, 560, 180, 32);

        jLabel34.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(242, 190, 94));
        jLabel34.setText("ODA NO");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(180, 560, 100, 24);

        txt_giristarihi.setBackground(new java.awt.Color(255, 255, 255));
        txt_giristarihi.setColumns(10);
        txt_giristarihi.setForeground(new java.awt.Color(242, 190, 94));
        try {
            txt_giristarihi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_giristarihi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_giristarihi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_giristarihiActionPerformed(evt);
            }
        });
        jPanel1.add(txt_giristarihi);
        txt_giristarihi.setBounds(290, 280, 180, 28);

        jLabel27.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(242, 190, 94));
        jLabel27.setText("GİRİŞ TARİHİ");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(120, 280, 170, 24);

        jLabel28.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(242, 190, 94));
        jLabel28.setText("KİMLİK/PASAPORT NO");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(10, 70, 274, 30);

        jLabel29.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(242, 190, 94));
        jLabel29.setText("DOĞUM TARİHİ");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(90, 240, 200, 24);

        jLabel30.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(242, 190, 94));
        jLabel30.setText("SOYİSİM");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(170, 160, 101, 24);

        jLabel31.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(242, 190, 94));
        jLabel31.setText("ÇIKIŞ TARİHİ");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(120, 320, 170, 24);

        txt_email.setBackground(new java.awt.Color(255, 255, 255));
        txt_email.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_email.setForeground(new java.awt.Color(242, 190, 94));
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        jPanel1.add(txt_email);
        txt_email.setBounds(290, 360, 180, 32);

        txt_telefonno.setBackground(new java.awt.Color(255, 255, 255));
        txt_telefonno.setColumns(15);
        txt_telefonno.setForeground(new java.awt.Color(242, 190, 94));
        try {
            txt_telefonno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("0(###)-###-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_telefonno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_telefonno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonnoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_telefonno);
        txt_telefonno.setBounds(290, 200, 180, 28);

        tbl.setBackground(new java.awt.Color(255, 255, 255));
        tbl.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        tbl.setForeground(new java.awt.Color(0, 0, 0));
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OdaNO", "ODA TİPİ", "KAT", "BALKON", "DURUM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl.setGridColor(new java.awt.Color(242, 190, 94));
        tbl.setName(""); // NOI18N
        tbl.setRowHeight(30);
        tbl.setSelectionBackground(new java.awt.Color(255, 214, 137));
        tbl.setSelectionForeground(new java.awt.Color(242, 190, 94));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(640, 70, 430, 560);

        jLabel7.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 190, 94));
        jLabel7.setText("YENİ MÜŞTERİ KAYIT");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(490, 10, 410, 41);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(242, 190, 94));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left-arrow.png"))); // NOI18N
        jButton1.setText("ANASAYFA");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 650, 200, 40);

        btn_kaydet.setBackground(new java.awt.Color(255, 255, 255));
        btn_kaydet.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        btn_kaydet.setForeground(new java.awt.Color(242, 190, 94));
        btn_kaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checked.png"))); // NOI18N
        btn_kaydet.setText("KAYDET");
        btn_kaydet.setBorder(null);
        btn_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaydetActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kaydet);
        btn_kaydet.setBounds(900, 650, 170, 40);

        cb_odatipi.setBackground(new java.awt.Color(255, 255, 255));
        cb_odatipi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cb_odatipi.setForeground(new java.awt.Color(242, 190, 94));
        cb_odatipi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEÇİNİZ" }));
        cb_odatipi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_odatipiActionPerformed(evt);
            }
        });
        jPanel1.add(cb_odatipi);
        cb_odatipi.setBounds(290, 500, 180, 34);

        jLabel6.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 190, 94));
        jLabel6.setText("ADRES");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(190, 430, 90, 24);

        txt_isim.setBackground(new java.awt.Color(255, 255, 255));
        txt_isim.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_isim.setForeground(new java.awt.Color(242, 190, 94));
        txt_isim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_isimActionPerformed(evt);
            }
        });
        jPanel1.add(txt_isim);
        txt_isim.setBounds(290, 120, 180, 32);

        jLabel22.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(242, 190, 94));
        jLabel22.setText("İSİM");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(210, 120, 60, 24);

        jLabel23.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(242, 190, 94));
        jLabel23.setText("TELEFON NO");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(110, 200, 170, 24);

        jLabel26.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(242, 190, 94));
        jLabel26.setText("ODA TİPİ");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(160, 500, 120, 24);

        txt_soyisim.setBackground(new java.awt.Color(255, 255, 255));
        txt_soyisim.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_soyisim.setForeground(new java.awt.Color(242, 190, 94));
        txt_soyisim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soyisimActionPerformed(evt);
            }
        });
        jPanel1.add(txt_soyisim);
        txt_soyisim.setBounds(290, 160, 180, 32);

        txt_dogumtarihi.setBackground(new java.awt.Color(255, 255, 255));
        txt_dogumtarihi.setColumns(10);
        txt_dogumtarihi.setForeground(new java.awt.Color(242, 190, 94));
        try {
            txt_dogumtarihi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_dogumtarihi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_dogumtarihi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dogumtarihiActionPerformed(evt);
            }
        });
        jPanel1.add(txt_dogumtarihi);
        txt_dogumtarihi.setBounds(290, 240, 180, 28);

        txt_kimlikno.setBackground(new java.awt.Color(255, 255, 255));
        txt_kimlikno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_kimlikno.setForeground(new java.awt.Color(242, 190, 94));
        txt_kimlikno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kimliknoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_kimlikno);
        txt_kimlikno.setBounds(290, 70, 180, 32);

        txt_adres.setBackground(new java.awt.Color(255, 255, 255));
        txt_adres.setColumns(20);
        txt_adres.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_adres.setForeground(new java.awt.Color(242, 190, 94));
        txt_adres.setRows(5);
        jScrollPane1.setViewportView(txt_adres);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(290, 410, 180, 70);

        txt_cikistarihi.setBackground(new java.awt.Color(255, 255, 255));
        txt_cikistarihi.setColumns(10);
        txt_cikistarihi.setForeground(new java.awt.Color(242, 190, 94));
        try {
            txt_cikistarihi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cikistarihi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_cikistarihi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cikistarihiActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cikistarihi);
        txt_cikistarihi.setBounds(290, 320, 180, 28);

        jLabel5.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 190, 94));
        jLabel5.setText("E-MAİL");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 370, 90, 24);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/26507_1100x700.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, -20, 1130, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1098, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    private void txt_soyisimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soyisimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soyisimActionPerformed

    private void txt_kimliknoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kimliknoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kimliknoActionPerformed

    private void txt_telefonnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonnoActionPerformed

    }//GEN-LAST:event_txt_telefonnoActionPerformed

    private void txt_isimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_isimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isimActionPerformed

    private void txt_dogumtarihiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dogumtarihiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dogumtarihiActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void cb_odatipiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_odatipiActionPerformed
       try{
           int secenek=cb_odatipi.getSelectedIndex();
            if (secenek==1) {
                 tablo_sil();
            conn = db.connect_db();
            String sql = "SELECT * FROM ODALAR WHERE ODATİPİ='TEK KİŞİLİK' AND ODADURUM='TEMİZ'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {

                String data[] = {rs.getString("ODANO"), rs.getString("ODATİPİ"), rs.getString("ODAKAT"),
                     rs.getString("ODABALKON"), rs.getString("ODADURUM")};
                DefaultTableModel tblModel = (DefaultTableModel) tbl.getModel();
                tblModel.addRow(data);
            }
            
           }
            if (secenek==2) {
                tablo_sil();
               conn = db.connect_db();
            String sql = "SELECT * FROM ODALAR WHERE ODATİPİ='ÇİFT KİŞİLİK' AND ODADURUM='TEMİZ'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {

                String data[] = {rs.getString("ODANO"), rs.getString("ODATİPİ"), rs.getString("ODAKAT"),
                rs.getString("ODABALKON"), rs.getString("ODADURUM")};
                DefaultTableModel tblModel = (DefaultTableModel) tbl.getModel();
                tblModel.addRow(data);
            }
            
           }
            if (secenek==3) {
                tablo_sil();
                conn = db.connect_db();
                String sql = "SELECT * FROM ODALAR WHERE ODATİPİ='ÜÇ KİŞİLİK' AND ODADURUM='TEMİZ'";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                
                while (rs.next()) {
                String data[] = {rs.getString("ODANO"), rs.getString("ODATİPİ"), rs.getString("ODAKAT"),
                rs.getString("ODABALKON"), rs.getString("ODADURUM")};
                
                DefaultTableModel tblModel = (DefaultTableModel) tbl.getModel();
                tblModel.addRow(data);
                }
            
           }
           
       }
       catch (Exception ex) {
           JOptionPane.showMessageDialog(null, "LİSTE GÖRÜNTÜLENEMİYOR.");
       }
       finally {
           try {
            conn.close();
           }
           catch (Exception ex) {
               
           }
           
       }
    }//GEN-LAST:event_cb_odatipiActionPerformed

    private void txt_cikistarihiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cikistarihiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cikistarihiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MusteriEkle C = new MusteriEkle();
        AnaSayfa B = new AnaSayfa();
        this.setVisible(false);
        B.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_giristarihiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_giristarihiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_giristarihiActionPerformed

    private void btn_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaydetActionPerformed
        ekleme();
        sifirla();
        tablo_sil();
        update();
        
        
    }//GEN-LAST:event_btn_kaydetActionPerformed

    private void txt_odanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_odanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_odanoActionPerformed

    
    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
      
        DefaultTableModel tblModel = (DefaultTableModel) tbl.getModel();
        String tblName= tblModel.getValueAt(tbl.getSelectedRow(), 0).toString();
        txt_odano.setText(tblName);
        
    }//GEN-LAST:event_tblMouseClicked

    /**
     * @param args the command line arguments
     */
    

    private void veri_list() {
        try {
            conn = db.connect_db();
            String sql = "SELECT * FROM ODALAR";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {

                String data[] = {rs.getString("ODANO"), rs.getString("ODATİPİ"), rs.getString("ODAKAT"),
                     rs.getString("ODABALKON"),};
                DefaultTableModel tblModel = (DefaultTableModel) tbl.getModel();
                tblModel.addRow(data);

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        } finally {
            try {
                conn.close();
            } catch (Exception e) {

            }
        }
    }
    
    public void odatipi() {
        try {
            conn = db.connect_db();
            String sql="SELECT DISTINCT ODATİPİ FROM ODALAR";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()) {
                cb_odatipi.addItem(rs.getString("ODATİPİ"));
            }
            
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        finally {
            try{
                conn.close();
            }
            catch(Exception ex) {
                
            }
        }
    }
   
   
    
     private void ekleme() {

        try {
            conn = db.connect_db();

            String sql = " INSERT INTO MUSTERİLER(TC,ISIM,SOYISIM,DOGUMTARIHI,TELEFONNO,GIRISTARIHI,CIKISTARIHI,EMAIL,ADRES,ODATIPI,ODANO) "
                    + "VALUES(?,?,?,?,?,?,?,?,?,?,?)";

            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_kimlikno.getText());
            pst.setString(2, txt_isim.getText());
            pst.setString(3, txt_soyisim.getText());
            pst.setString(4, txt_dogumtarihi.getText());
            pst.setString(5, txt_telefonno.getText());
            pst.setString(6, txt_giristarihi.getText());
            pst.setString(7, txt_cikistarihi.getText());
            pst.setString(8, txt_email.getText());
            pst.setString(9, txt_adres.getText());
            pst.setString(10, cb_odatipi.getSelectedItem().toString());
            pst.setString(11, txt_odano.getText());

            pst.execute();

            JOptionPane.showMessageDialog(null, "Kayıt Oluşturuldu ");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Kayıt Gerçekleştirilemedi.");
        } finally {
            try {
                conn.close();
            } catch (Exception e) {

            }
        }

    }
     
     public void update()
    {
        try
        {
            int odano = Integer.parseInt(txt_odano.getText());
            conn = db.connect_db();
            String sql = "UPDATE ROOMS SET ROOM_STATUS='DIRTY' WHERE (ROOM_NO = ? AND ROOM_STATUS='CLEAN')";
            pst = conn.prepareStatement(sql);
            pst.setInt(1, odano); // Here you set the value of the ? parameter
            int updateCount = pst.executeUpdate(); // You are executing an update, so you don't get a `ResultSet` you get an integer that shows how many rows were updated.
        }
        catch (Exception ex)
        {
            ex.printStackTrace(); // Important !
        }
        finally {
            try {
                conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }

     
     public void sifirla() {

        txt_isim.setText("");
        txt_soyisim.setText("");
        txt_dogumtarihi.setText("");
        txt_kimlikno.setText("");
        txt_telefonno.setText("");
        txt_giristarihi.setText("");
        txt_cikistarihi.setText("");
        txt_email.setText("");
        txt_adres.setText("");
        cb_odatipi.setSelectedIndex(0);
        txt_odano.setText("");

    }
     
     public void tablo_sil() {
        try {
        DefaultTableModel odalistesi = (DefaultTableModel)tbl.getModel();
        odalistesi.getDataVector().removeAllElements();
        tbl.repaint();
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"");
        }
    }
     
     
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusteriEkle().setVisible(true);
            }
        });
    }

    
    
         
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kaydet;
    private javax.swing.JComboBox<String> cb_odatipi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl;
    private javax.swing.JTextArea txt_adres;
    private javax.swing.JFormattedTextField txt_cikistarihi;
    private javax.swing.JFormattedTextField txt_dogumtarihi;
    private javax.swing.JTextField txt_email;
    private javax.swing.JFormattedTextField txt_giristarihi;
    private javax.swing.JTextField txt_isim;
    private javax.swing.JTextField txt_kimlikno;
    private javax.swing.JTextField txt_odano;
    private javax.swing.JTextField txt_soyisim;
    private javax.swing.JFormattedTextField txt_telefonno;
    // End of variables declaration//GEN-END:variables

    
}
